name: daps
nsteps: 100
nsamples: 1

parameters:
  lr: 1e-5
  tau: 0.005
  lr_min_ratio: 0.001
  lgv_steps: 50
  debug_plots: False

  annealing_scheduler_config:
    num_steps: 200
    sigma_max: 20
    sigma_min: 0.001
    sigma_final: 0
    schedule: 'linear'
    timestep: 'poly-7'

  diffusion_scheduler_config:
    num_steps: 5
    sigma_min: 0.0001
    sigma_final: 0
    schedule: 'linear'
    timestep: 'poly-7'
