# configuration taken from main paper https://arxiv.org/pdf/2405.18782
# from Table 3 and Table 4
name: pnp_dm
nsteps: 100
nsamples: 1

parameters:
  rho_start: 10
  rho_decay_rate: 0.9
  rho_min: 0.001
  mode: ve
  use_ode: False
  force_use_langevin: True
  langevin_stepsize: 1e-9
  n_langevin_steps: 100
